/*
  Generated by Make DParser Version 1.26.mCRL2
  Available at http://dparser.sf.net
*/

#ifndef _fsm_h
#define _fsm_h
#define D_START_STATE_FSM 	1
#define D_START_STATE_Separator 	2
#define D_START_STATE_ParameterList 	3
#define D_START_STATE_Parameter 	4
#define D_START_STATE_ParameterName 	5
#define D_START_STATE_DomainCardinality 	6
#define D_START_STATE_SortExpr 	7
#define D_START_STATE_DomainValueList 	8
#define D_START_STATE_DomainValue 	9
#define D_START_STATE_StateList 	10
#define D_START_STATE_State 	11
#define D_START_STATE_TransitionList 	12
#define D_START_STATE_Transition 	13
#define D_START_STATE_Distribution 	14
#define D_START_STATE_ProbabilisticStateElement 	15
#define D_START_STATE_ProbabilisticState 	16
#define D_START_STATE_InitialState 	17
#define D_START_STATE_Source 	18
#define D_START_STATE_Target 	19
#define D_START_STATE_Label 	20
#define D_START_STATE_QuotedString 	21
#define D_START_STATE_Id 	22
#define D_START_STATE_Number 	23
#define D_START_STATE_EOLN 	24
#define D_START_STATE_whitespace 	25
#endif
